### ISSUE TITLE
Question: What's the CHANGELOG format used for this project?

### ISSUE THREAD

**Issue by dellagustin-sap** [tkellen/js-express-bearer-token#27]
Hi, 

I'm interested in learning more about the format that is used for https://github.com/tkellen/js-express-bearer-token/blob/master/CHANGELOG.

It seems to be in a yaml format. Is this some kind of "standard" or was it defined arbitrarily for this project?

The reason for the question is because I'm interested in researching different CHANGELOG standards for recommending to projects where I'm involved.

Best Regards.

**Comment by tkellen** [comment]
It was defined arbitrarily for this project. You are welcome to do whatever you wish with it.

**Comment by dellagustin-sap** [comment]
@tkellen , thank you for the reply!
